metadata:
  id: TC24343
  name: Settings - Add Finance Account
  feature: test-cases
  priority: high
  platforms:
  - iOS
  - Android
  regions:
  - USA
  tags: []
  created: '2024-10-18'
  updated: '2024-10-24'
  author: user_17
  testmo_id: 66304
  folder_id: 3085
preconditions:
- description: Login with an NCF account > https://www.notion.so/bethinklabs/d0f8f58385a94c51ab27ce3ee1ef1e51?v=caf06428a7ac41aa96541666be242cd7
- description: NCF Account Connected or Disconnected
